image: node:18

pipelines:
  branches:
    develop:
      - step:
          name: Deploy to EC2
          deployment: production
          script:
            - echo "Deploying to EC2..."
            
            
            - mkdir -p ~/.ssh
            - echo "$EC2_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            - chmod 600 ~/.ssh/id_rsa

            
            - ssh-keyscan -H 54.224.182.102 >> ~/.ssh/known_hosts

            
            - ssh ubuntu@54.224.182.102 << EOF
                cd ~/nodejs-app
                git pull origin develop
                npm install
                pm2 restart my-node-app
              EOF
